d /var/lib/the-den 0750 the-den the-den -
d /var/lib/the-den/movies 0750 the-den the-den -
d /var/lib/the-den/tv 0750 the-den the-den -
d /var/lib/the-den/downloads 0750 the-den the-den -
d /var/lib/the-den/state 0750 the-den the-den -
