// GENERATED by design/build_tokens.py from design/tokens.json -- do not edit by hand.
// Copy into the-den-android/app/src/main/kotlin/com/holtos/theden/ui/theme/ and build the
// Material3 ColorScheme from these. Colours are 0xAARRGGBB Longs for androidx.compose.ui.graphics.Color.
package com.holtos.theden.ui.theme

import androidx.compose.ui.graphics.Color

object HoltTokens {
    object Palette {
        val deep = Color(0xFF0D0B12)
        val surface = Color(0xFF171423)
        val raised = Color(0xFF1D1927)
        val hairline = Color(0x17FFFFFF)
        val hairlineStrong = Color(0x26FFFFFF)
        val ink = Color(0xFFFFFFFF)
        val ink70 = Color(0xB2FFFFFF)
        val ink55 = Color(0x8CFFFFFF)
        val ink42 = Color(0x6BFFFFFF)
        val ink28 = Color(0x47FFFFFF)
        val current = Color(0xFFB14DFF)
        val currentHover = Color(0xFFC77DFF)
        val currentDeep = Color(0xFF8F2FE0)
        val currentTint = Color(0x1AB14DFF)
        val lilac = Color(0xFFF4EBFF)
        val healthy = Color(0xFF28E0C8)
        val warning = Color(0xFFFFB84D)
    }
    object Glass {
        val surface = Color(0xB2171423)
        val surfaceStrong = Color(0xD6171423)
        val border = Color(0x17FFFFFF)
        val borderStrong = Color(0x26FFFFFF)
        val highlight = Color(0x0FFFFFFF)
        val highlightStrong = Color(0x14FFFFFF)
        val blurDp = 18
        val blurStrongDp = 28
        val blurBadgeDp = 8
        val saturate = 1.4f
        val badgeSurface = Color(0xB80D0B12)
        val inputSurface = Color(0x800D0B12)
    }
    object Ambient {
        val glowCurrent = Color(0x2EB14DFF)
        val glowHealthy = Color(0x1228E0C8)
        val ring = Color(0x0DF4EBFF)
        val scrimStrong = Color(0xEB0D0B12)
        val scrimMid = Color(0x9E0D0B12)
        val scrimWeak = Color(0x1F0D0B12)
        val stripe = Color(0x3DB14DFF)
    }
    object Badge {
        val available = Color(0xFF28E0C8)
        val pending = Color(0xFFB14DFF)
        val processing = Color(0xFFB14DFF)
        val partial = Color(0xFFFFB84D)
        val error = Color(0xFFFFB84D)
        val missing = Color(0x6BFFFFFF)
        val missingDot = Color(0x47FFFFFF)
    }
    object Radius {
        val sm = 8
        val md = 10
        val lg = 14
        val pill = 999
    }
    object Space {
        val s1 = 6
        val s2 = 10
        val s3 = 16
        val s4 = 22
        val s5 = 32
        val s6 = 48
    }
    object Size {
        val sidebar = 240
        val sidebarRail = 72
        val topBar = 60
        val tabBar = 72
        val contentMax = 1400
        val posterSm = 112
        val posterMd = 132
        val posterLg = 148
        val posterXl = 220
        val avatar = 28
        val hitTarget = 44
        val mobileBreakpoint = 900
    }
    object Motion {
        val fastMs = 160
        val baseMs = 220
        val drawMs = 1600
    }
    object Type {
        val display = TypeSpec(size = 42f, weight = 900, tracking = -1.8f, lineHeight = 0.98f, mono = false, uppercase = false)
        val displayHero = TypeSpec(size = 64f, weight = 900, tracking = -2.6f, lineHeight = 0.95f, mono = false, uppercase = false)
        val pageTitle = TypeSpec(size = 26f, weight = 800, tracking = -1.2f, lineHeight = 1.05f, mono = false, uppercase = false)
        val sectionTitle = TypeSpec(size = 16f, weight = 800, tracking = -0.4f, lineHeight = 1.2f, mono = false, uppercase = false)
        val wordmark = TypeSpec(size = 20f, weight = 900, tracking = -0.6f, lineHeight = 1f, mono = false, uppercase = false)
        val body = TypeSpec(size = 15f, weight = 400, tracking = 0f, lineHeight = 1.6f, mono = false, uppercase = false)
        val bodySmall = TypeSpec(size = 13f, weight = 400, tracking = 0f, lineHeight = 1.55f, mono = false, uppercase = false)
        val label = TypeSpec(size = 13.5f, weight = 700, tracking = 0f, lineHeight = 1.2f, mono = false, uppercase = false)
        val button = TypeSpec(size = 12.5f, weight = 800, tracking = -0.2f, lineHeight = 1f, mono = false, uppercase = false)
        val eyebrow = TypeSpec(size = 10.5f, weight = 400, tracking = 2.2f, lineHeight = 1.2f, mono = true, uppercase = true)
        val meta = TypeSpec(size = 10.5f, weight = 400, tracking = 0f, lineHeight = 1.7f, mono = true, uppercase = false)
        val fieldLabel = TypeSpec(size = 10.5f, weight = 400, tracking = 1.2f, lineHeight = 1.2f, mono = true, uppercase = true)
    }
}

data class TypeSpec(val size: Float, val weight: Int, val tracking: Float, val lineHeight: Float, val mono: Boolean, val uppercase: Boolean)
