"""Generate every implementation's token file from design/tokens.json.

    python design/build_tokens.py          # writes all outputs
    python design/build_tokens.py --check  # exit 1 if any output is stale (for CI / pre-commit)

Outputs:
  app/static/holt-tokens.css     the web UI's CSS custom properties (+ reduced-transparency
                                 and reduced-motion overrides, so components that use the
                                 tokens degrade automatically)
  design/exports/holt_tokens.py  a plain dict for the KDE client's theme.py (PySide6)
  design/exports/HoltTokens.kt   a Kotlin object for the Android client's theme

The two exports are copied into the companion repos by hand (they are separate repos);
this script only keeps them generated from the same numbers.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "design" / "tokens.json"
OUT_CSS = ROOT / "app" / "static" / "holt-tokens.css"
OUT_PY = ROOT / "design" / "exports" / "holt_tokens.py"
OUT_KT = ROOT / "design" / "exports" / "HoltTokens.kt"

GENERATED = "GENERATED by design/build_tokens.py from design/tokens.json -- do not edit by hand."


def _kebab(name: str) -> str:
    return re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", name).lower()


def _snake(name: str) -> str:
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name).lower()


def _pascal(name: str) -> str:
    return name[0].upper() + name[1:]


# ---------------------------------------------------------------- CSS ------------

def build_css(t: dict) -> str:
    c, g, a, b, f, r, s, sz, sh, m = (
        t["color"], t["glass"], t["ambient"], t["badge"], t["font"],
        t["radius"], t["space"], t["size"], t["shadow"], t["motion"],
    )
    lines = [f"/* {GENERATED} */", f"@import url('{f['googleFonts']}');", "", ":root{"]

    def group(comment: str, prefix: str, items: dict, unit: str = "") -> None:
        lines.append(f"  /* {comment} */")
        for k, v in items.items():
            lines.append(f"  --holt-{prefix}{_kebab(k)}:{v}{unit};")
        lines.append("")

    lines.append("  /* Core surfaces -- HoltOS is a dark system first */")
    for k in ("deep", "surface", "raised", "hairline", "hairlineStrong"):
        lines.append(f"  --holt-{_kebab(k)}:{c[k]};")
    lines.append("")
    lines.append("  /* Ink */")
    for k in ("ink", "ink70", "ink55", "ink42", "ink28"):
        lines.append(f"  --holt-{k[:3]}{'-' + k[3:] if k[3:] else ''}:{c[k]};")
    lines.append("")
    lines.append("  /* Identity -- purple carries identity and does the shouting */")
    for k in ("current", "currentHover", "currentDeep", "currentTint", "lilac"):
        lines.append(f"  --holt-{_kebab(k)}:{c[k]};")
    lines.append("")
    lines.append("  /* Semantic -- teal ONLY ever means online / healthy; amber means a human is needed */")
    for k in ("healthy", "warning"):
        lines.append(f"  --holt-{k}:{c[k]};")
    lines.append("")
    group("Glass (HoltOS Glass v2): translucent surfaces that blur what is behind them", "glass-", g)
    group("Ambient ground layer + scrims for text over art", "ambient-", a)
    group("Badges (status on media)", "badge-", b)
    lines.append("  /* Type */")
    lines.append(f"  --holt-font-core:{f['core']};")
    lines.append(f"  --holt-font-mono:{f['mono']};")
    lines.append("")
    group("Geometry", "radius-", r, "px")
    group("Rhythm", "space-", s, "px")
    group("Layout sizes", "size-", sz, "px")
    group("Elevation", "shadow-", sh)
    lines[-1] = "  --holt-shadow:var(--holt-shadow-1); /* back-compat alias */"
    lines.append("")
    group("Motion -- drawn, never spun", "dur-", {"fast": m["fast"], "base": m["base"], "draw": m["draw"]})
    lines.append(f"  --holt-ease-out:{m['easeOut']};")
    lines.append("}")
    lines.append("")
    lines.append("/* Reduced transparency: every glass surface becomes its opaque twin, so any component")
    lines.append("   built on the tokens degrades without its own media query. */")
    lines.append("@media (prefers-reduced-transparency: reduce){")
    lines.append("  :root{")
    lines.append(f"    --holt-glass-surface:{c['surface']};")
    lines.append(f"    --holt-glass-surface-strong:{c['surface']};")
    lines.append(f"    --holt-glass-badge-surface:{c['deep']};")
    lines.append(f"    --holt-glass-input-surface:{c['deep']};")
    lines.append("    --holt-glass-blur:0px;")
    lines.append("    --holt-glass-blur-strong:0px;")
    lines.append("    --holt-glass-blur-badge:0px;")
    lines.append("    --holt-glass-saturate:100%;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("@media (prefers-reduced-motion: reduce){")
    lines.append("  :root{--holt-dur-fast:0ms;--holt-dur-base:0ms;--holt-dur-draw:0ms}")
    lines.append("}")
    lines.append("")
    lines.append("body{margin:0;background:var(--holt-deep);color:var(--holt-ink);font-family:var(--holt-font-core);-webkit-font-smoothing:antialiased}")
    lines.append("a{color:var(--holt-current);text-decoration:none}")
    lines.append("a:hover{color:var(--holt-current-hover)}")
    lines.append("")
    lines.append("/* Type roles */")
    ty = t["type"]

    def role(cls: str, key: str, extra: str = "") -> None:
        d = ty[key]
        fam = "var(--holt-font-mono)" if d.get("mono") else "var(--holt-font-core)"
        parts = [f"font-family:{fam}", f"font-weight:{d['weight']}", f"font-size:{d['size']}px",
                 f"letter-spacing:{d['tracking']}px", f"line-height:{d['lineHeight']}"]
        if d.get("uppercase"):
            parts.append("text-transform:uppercase")
        lines.append(f".holt-{cls}{{{';'.join(parts)}{extra}}}")

    role("display", "displayHero")
    role("display-lg", "display")
    role("title", "pageTitle")
    role("body", "body", ";color:var(--holt-ink-55);text-wrap:pretty")
    role("eyebrow", "eyebrow", ";color:var(--holt-healthy)")
    role("meta", "meta", ";color:var(--holt-ink-42)")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------- Python ---------

def _rgba_to_argb_hex(value: str) -> str:
    """'rgba(255,255,255,.09)' -> '#17FFFFFF' (Qt's #AARRGGBB). '#RRGGBB' passes through as #FFRRGGBB."""
    if value.startswith("#"):
        return "#FF" + value[1:].upper() if len(value) == 7 else value.upper()
    m = re.match(r"rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+))?\s*\)", value)
    if not m:
        raise ValueError(f"unparseable colour: {value}")
    r, g, b = (int(m.group(i)) for i in (1, 2, 3))
    a = round(float(m.group(4) or 1) * 255)
    return f"#{a:02X}{r:02X}{g:02X}{b:02X}"


def build_py(t: dict) -> str:
    lines = [f'"""{GENERATED}', "", "Colours are Qt-style '#AARRGGBB' strings (alpha FIRST -- not CSS's #RRGGBBAA; this is the",
             "bug that tests/check_theme_colors.py in the-den-client exists to catch). Sizes are ints in px,",
             'durations in ms. Copy this file into the-den-client/src/ and have theme.py read from it."""', ""]
    for section in ("color", "glass", "ambient", "badge"):
        lines.append(f"{section.upper()} = {{")
        for k, v in t[section].items():
            if k.startswith("blur") or k == "saturate":
                lines.append(f"    {_snake(k)!r}: {v!r},")
            else:
                lines.append(f"    {_snake(k)!r}: {_rgba_to_argb_hex(v)!r},")
        lines.append("}")
        lines.append("")
    lines.append(f"FONT_CORE = {t['font']['coreFamily']!r}")
    lines.append(f"FONT_MONO = {t['font']['monoFamily']!r}")
    lines.append("")
    lines.append("TYPE = {")
    for k, d in t["type"].items():
        lines.append(f"    {_snake(k)!r}: {{'size': {d['size']}, 'weight': {d['weight']}, 'tracking': {d['tracking']}, 'line_height': {d['lineHeight']}, 'mono': {bool(d.get('mono'))}, 'uppercase': {bool(d.get('uppercase'))}}},")
    lines.append("}")
    lines.append("")
    for section in ("radius", "space", "size"):
        lines.append(f"{section.upper()} = {{")
        for k, v in t[section].items():
            lines.append(f"    {str(k)!r}: {v},")
        lines.append("}")
        lines.append("")
    lines.append("MOTION_MS = {")
    for k in ("fast", "base", "draw"):
        lines.append(f"    {k!r}: {int(t['motion'][k].rstrip('ms'))},")
    lines.append("}")
    lines.append(f"EASE_OUT = {t['motion']['easeOut']!r}  # cubic-bezier control points")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------- Kotlin ---------

def build_kt(t: dict) -> str:
    lines = [f"// {GENERATED}", "// Copy into the-den-android/app/src/main/kotlin/com/holtos/theden/ui/theme/ and build the",
             "// Material3 ColorScheme from these. Colours are 0xAARRGGBB Longs for androidx.compose.ui.graphics.Color.",
             "package com.holtos.theden.ui.theme", "", "import androidx.compose.ui.graphics.Color", "", "object HoltTokens {"]
    # "Palette", not "Color": a nested object named Color would shadow Compose's Color type.
    kt_names = {"color": "Palette", "glass": "Glass", "ambient": "Ambient", "badge": "Badge"}
    for section in ("color", "glass", "ambient", "badge"):
        lines.append(f"    object {kt_names[section]} {{")
        for k, v in t[section].items():
            if k.startswith("blur"):
                lines.append(f"        val {k}Dp = {int(v.rstrip('px'))}")
            elif k == "saturate":
                lines.append(f"        val saturate = {int(v.rstrip('%')) / 100}f")
            else:
                argb = _rgba_to_argb_hex(v)[1:]
                lines.append(f"        val {k} = Color(0x{argb})")
        lines.append("    }")
    lines.append("    object Radius {")
    for k, v in t["radius"].items():
        lines.append(f"        val {k} = {v}")
    lines.append("    }")
    lines.append("    object Space {")
    for k, v in t["space"].items():
        lines.append(f"        val s{k} = {v}")
    lines.append("    }")
    lines.append("    object Size {")
    for k, v in t["size"].items():
        lines.append(f"        val {k} = {v}")
    lines.append("    }")
    lines.append("    object Motion {")
    for k in ("fast", "base", "draw"):
        lines.append(f"        val {k}Ms = {int(t['motion'][k].rstrip('ms'))}")
    lines.append("    }")
    lines.append("    object Type {")
    for k, d in t["type"].items():
        lines.append(f"        val {k} = TypeSpec(size = {d['size']}f, weight = {d['weight']}, tracking = {d['tracking']}f, lineHeight = {d['lineHeight']}f, mono = {str(bool(d.get('mono'))).lower()}, uppercase = {str(bool(d.get('uppercase'))).lower()})")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("data class TypeSpec(val size: Float, val weight: Int, val tracking: Float, val lineHeight: Float, val mono: Boolean, val uppercase: Boolean)")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------- main -----------

def main(argv: list[str]) -> int:
    tokens = json.loads(TOKENS.read_text(encoding="utf-8"))
    outputs = {OUT_CSS: build_css(tokens), OUT_PY: build_py(tokens), OUT_KT: build_kt(tokens)}
    check = "--check" in argv
    stale = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8", newline="\n")
    rel = [str(p.relative_to(ROOT)) for p in stale]
    if check:
        if stale:
            print("stale (run python design/build_tokens.py):", ", ".join(rel))
            return 1
        print("tokens up to date")
        return 0
    print("wrote:" if stale else "up to date:", ", ".join(rel) or "nothing changed")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
