"""add settings table

Revision ID: 93e0b8e54d80
Revises: d8c9a26cd55d
Create Date: 2026-09-07 21:06:55.979645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e0b8e54d80'
down_revision: Union[str, Sequence[str], None] = 'd8c9a26cd55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_api_key', sa.String(), nullable=True),
    sa.Column('qbit_url', sa.String(), nullable=True),
    sa.Column('qbit_username', sa.String(), nullable=True),
    sa.Column('qbit_password', sa.String(), nullable=True),
    sa.Column('movies_root', sa.String(), nullable=True),
    sa.Column('tv_root', sa.String(), nullable=True),
    sa.Column('automation_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('discord_webhook_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
