"""rename series.tmdb_id to tvmaze_id

Revision ID: d8c9a26cd55d
Revises: 0193ce7e1345
Create Date: 2026-09-07 21:01:03.788314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c9a26cd55d'
down_revision: Union[str, Sequence[str], None] = '0193ce7e1345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tvmaze_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_series_tvmaze_id', ['tvmaze_id'])
        batch_op.drop_column('tmdb_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('uq_series_tvmaze_id', type_='unique')
        batch_op.drop_column('tvmaze_id')

    # ### end Alembic commands ###
